name: 'Checkout QMK firmware'

inputs:
  path:
    default: '__qmk__'
    type: string
    required: false

runs:
  using: 'composite'
  steps:

  - name: Checkout qmk_firmware
    uses: actions/checkout@v4
    with:
      path: ${{ inputs.path }}
      repository: gamoutatsumi/qmk_firmware
      submodules: recursive

  - name: Setup QMK
    shell: bash
    run: qmk setup --home ${{ inputs.path }} --yes
